### ISSUE TITLE
连接到直接提供公网ip的公共wifi（如部分校园网wifi）下出现自身回环的情况

### ISSUE THREAD

**Issue by wsvg14** [CerteKim/Xray4Magisk#14]
脚本为最新版本，除proxy外全部为默认
现象是在试图连接直接提供公网ip的wifi下，在尝试连接时均会无法联网
access.log下出现大量自身从wifi得到的ip回环

以下为节选（xxx.xxx.xxx.xxx为wifi得到ip）

2021/03/14 07:39:04 xxx.xxx.xxx.xxx:44158 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:39099 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:41707 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:49905 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:40968 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:37829 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:42639 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:39089 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:41719 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:41409 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:43374 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:44849 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:37925 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:47694 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:47735 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:41404 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:38619 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:40192 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:49884 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:44232 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:38600 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:44244 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:49553 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]
2021/03/14 07:39:04 xxx.xxx.xxx.xxx:37696 accepted udp:xxx.xxx.xxx.xxx:68 [proxy-in -> direct]

**Comment by CerteKim** [comment]
看起来是 DHCP 请求通过了 xray，然后不知道在什么地方丢掉了。

error.log 中是否有更多信息？

**Comment by wsvg14** [comment]
以下为error.log节选
出错时此文件体积暴涨，短时间内暴涨到几十m

2021/03/15 06:33:35 [Debug] [2734412923] proxy/dokodemo: processing connection from: 218.194.45.87:56653
2021/03/15 06:33:35 [Info] [2734412923] proxy/dokodemo: received request for 218.194.45.87:56653
2021/03/15 06:33:35 [Info] [2734412923] app/dispatcher: taking detour [direct] for [udp:218.194.47.255:5684]
2021/03/15 06:33:35 [Info] [2734412923] proxy/freedom: opening connection to udp:218.194.47.255:5684
2021/03/15 06:33:35 [Info] [2054717287] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > write udp [::]:41993->113.54.223.255:5684: sendto: network is unreachable
2021/03/15 06:33:35 [Info] [2054717287] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/03/15 06:33:35 [Info] [2734412923] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > write udp [::]:41045->218.194.47.255:5684: sendto: network is unreachable
2021/03/15 06:33:35 [Info] [2734412923] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/03/15 06:33:35 [Debug] transport/internet/udp: UDP original destination: udp:211.83.102.255:137
2021/03/15 06:33:35 [Debug] [3648216823] proxy/dokodemo: processing connection from: 211.83.102.134:137
2021/03/15 06:33:35 [Info] [3648216823] proxy/dokodemo: received request for 211.83.102.134:137
2021/03/15 06:33:35 [Info] [3648216823] app/dispatcher: taking detour [direct] for [udp:211.83.102.255:137]
2021/03/15 06:33:35 [Info] [3648216823] proxy/freedom: opening connection to udp:211.83.102.255:137
2021/03/15 06:33:35 [Info] [3648216823] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > write udp [::]:38283->211.83.102.255:137: sendto: network is unreachable
2021/03/15 06:33:35 [Info] [3648216823] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/03/15 06:33:35 [Debug] transport/internet/udp: UDP original destination: udp:xxx.xxx.xxx.xcc:5684
2021/03/15 06:33:35 [Debug] [1690462365] proxy/dokodemo: processing connection from: 222.197.169.88:48779
2021/03/15 06:33:35 [Info] [1690462365] proxy/dokodemo: received request for 222.197.169.88:48779
2021/03/15 06:33:35 [Info] [1690462365] app/dispatcher: taking detour [direct] for [udp:xxx.xxx.xxx.xcc:5684]
2021/03/15 06:33:35 [Info] [1690462365] proxy/freedom: opening connection to udp:xxx.xxx.xxx.xcc:5684
2021/03/15 06:33:35 [Info] [1690462365] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > write udp [::]:41947->xxx.xxx.xxx.xcc:5684: sendto: network is unreachable
2021/03/15 06:33:35 [Info] [1690462365] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/03/15 06:33:35 [Debug] transport/internet/udp: UDP original destination: udp:xxx.xxx.xxx.xcc:5684
2021/03/15 06:33:35 [Debug] [2892565270] proxy/dokodemo: processing connection from: xxx.xxx.xxx.xxx:52889
2021/03/15 06:33:35 [Info] [2892565270] proxy/dokodemo: received request for xxx.xxx.xxx.xxx:52889
2021/03/15 06:33:35 [Info] [2892565270] app/dispatcher: taking detour [direct] for [udp:xxx.xxx.xxx.xcc:5684]
2021/03/15 06:33:35 [Info] [2892565270] proxy/freedom: opening connection to udp:xxx.xxx.xxx.xcc:5684
2021/03/15 06:33:35 [Info] [2892565270] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > proxy/freedom: failed to process request > write udp [::]:41145->xxx.xxx.xxx.xcc:5684: sendto: network is unreachable
2021/03/15 06:33:35 [Info] [2892565270] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/03/15 06:33:35 [Debug] transport/internet/udp: UDP original destination: udp:218.194.47.255:5684
2021/03/15 06:33:35 [Debug] [1245574189] proxy/dokodemo: processing connection from: 218.194.45.171:57317
2021/03/15 06:33:35 [Info] [1245574189] proxy/dokodemo: received request for 218.194.45.171:57317

**Comment by CerteKim** [comment]
#### 可能需要手动修改 xray.tproxy，把此 wifi 提供的公网网段加入到 intranet 数组中

#### 或者在 tproxy 中 bypass 掉 68 端口的请求
替换
```
        # mark all traffic
        ${iptables} -t mangle -A XRAY -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port ${proxy_port} --tproxy-mark ${mark_id}
        ${iptables} -t mangle -A XRAY -p udp -j TPROXY --on-ip 127.0.0.1 --on-port ${proxy_port} --tproxy-mark ${mark_id}
```
为
```
        # bypass 68
        ${iptables} -t mangle -A XRAY -p tcp ! --dport 68 -j TPROXY --on-port ${proxy_port} --tproxy-mark ${mark_id}
        ${iptables} -t mangle -A XRAY -p udp ! --dport68 -j TPROXY --on-port ${proxy_port} --tproxy-mark ${mark_id}
```

**Comment by wsvg14** [comment]
> #### 可能需要手动修改 xray.tproxy，把此 wifi 提供的公网网段加入到 intranet 数组中
> #### 或者在 tproxy 中 bypass 掉来源为 68 端口的请求 / or 目标为 67 端口的请求
> 替换
> 
> ```
>         # mark all traffic
>         ${iptables} -t mangle -A XRAY -p tcp -j TPROXY --on-ip 127.0.0.1 --on-port ${proxy_port} --tproxy-mark ${mark_id}
>         ${iptables} -t mangle -A XRAY -p udp -j TPROXY --on-ip 127.0.0.1 --on-port ${proxy_port} --tproxy-mark ${mark_id}
> ```
> 
> 为
> 
> ```
>         # bypass 67
>         ${iptables} -t mangle -A XRAY -p tcp ! --dport 67 -j TPROXY --on-port ${proxy_port} --tproxy-mark ${mark_id}
>         ${iptables} -t mangle -A XRAY -p udp ! --dport 67 -j TPROXY --on-port ${proxy_port} --tproxy-mark ${mark_id}
> ```
> 
> 或者
> 
> ```
>         # bypass 68
>         ${iptables} -t mangle -A XRAY -p tcp ! --sport 68 -j TPROXY --on-port ${proxy_port} --tproxy-mark ${mark_id}
>         ${iptables} -t mangle -A XRAY -p udp ! --sport 68 -j TPROXY --on-port ${proxy_port} --tproxy-mark ${mark_id}
> ```

方法1：使用网络环境获得公网ip实际不固定而且在校区内各地拿到公网ip网段均不同，此方法不现实
方法2：无效，似乎端口会变化

附加：即便是正常使用，在开机时可能导致手机上应用大量消耗cpu资源

**Comment by CerteKim** [comment]
请提供一下 service.log。

**Comment by wsvg14** [comment]
> 请提供一下 service.log。

[Info]: Starting xray service.
[Error]: Start xray service Failed.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
[Info]: xray service is stopped.
[Info]: Starting xray service.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
cleaning ipv4
[Info]: creating mangle chain
netstat: /proc/1750: No such file or directory
[Info]: creating proxy
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
[Info]: xray service is running. ( PID: 1578 )
Broadcast completed: result=0
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
Broadcast completed: result=0
using ipv4
[Info]: cleaning mangle iptables
[Info]: xray service is running. ( PID: 1578 )
[Info]: Stopping xray service.
[Info]: xray service is stopped.
[Info]: Starting xray service.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
cleaning ipv4
[Info]: creating mangle chain
netstat: /proc/8549: No such file or directory
[Info]: creating proxy
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
[Info]: xray service is running. ( PID: 8522 )
Broadcast completed: result=0
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
Broadcast completed: result=0
using ipv4
[Info]: cleaning mangle iptables
[Info]: xray service is running. ( PID: 8522 )
[Info]: Stopping xray service.
[Info]: xray service is stopped.

顺带发现如果手机初次启动时error.log会出现这个情况

Xray 1.3.1 (Xray, Penetrates Everything.) Custom (go1.16 android/arm64)
A unified platform for anti-censorship.
2021/03/15 11:42:27 Using confdir from arg: /data/xray/confs
2021/03/15 11:42:27 [Info] infra/conf/serial: Reading config: /data/xray/confs/base.json
2021/03/15 11:42:27 [Info] infra/conf/serial: Reading config: /data/xray/confs/dns.json
2021/03/15 11:42:27 [Info] infra/conf/serial: Reading config: /data/xray/confs/proxy.json
Failed to start: main: failed to load config files: [/data/xray/confs/base.json /data/xray/confs/dns.json /data/xray/confs/proxy.json /data/xray/confs/routing.json /data/xray/confs/xray-api.json] > infra/conf/serial: failed to read config: /data/xray/confs/proxy.json > open /data/xray/confs/proxy.json: required key not available

必须重启一次才行

**Comment by CerteKim** [comment]
日志看着非常杂乱。。建议在 magisk manager 开启模块的情况下重启手机，等一段时间之后再关闭模块，然后将 service.log 发过来
以及，proxy.json 是否正确配置。

**Comment by wsvg14** [comment]
刚启动手机时在service.log均有
[Info]: Starting xray service.
netstat: /proc/3536: No such file or directory
[Error]: Start xray service Failed.

怀疑启动时并不能获得相应uid
而且仍然需要开关一次模块才可获得信息

正常时
[Info]: Starting xray service.
[Error]: Start xray service Failed.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
[Info]: xray service is stopped.
[Info]: Starting xray service.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
cleaning ipv4
[Info]: creating mangle chain
netstat: /proc/2723: No such file or directory
[Warning]: xray service is running but may not listening. ( PID: 2675 )
[Info]: creating proxy
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
Broadcast completed: result=0
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
Broadcast completed: result=0
异常状态
[Info]: Starting xray service.
netstat: /proc/3536: No such file or directory
[Error]: Start xray service Failed.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
[Info]: xray service is stopped.
[Info]: Starting xray service.
RTNETLINK answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
cleaning ipv4
[Info]: creating mangle chain
[Info]: creating proxy
Broadcasting: Intent { act=android.intent.action.AIRPLANE_MODE flg=0x400000 }
[Info]: xray service is running. ( PID: 25567 )

似乎看不出来区别

**Comment by CerteKim** [comment]
奇怪的是有一句 Start xray service Failed.

**Comment by wsvg14** [comment]
在使用kalasutra/Clash_For_Magisk早期tproxy版本的时候也会有这个问题
目前那里的解决办法是在每次启动时就探测现有连接到wifi获取的ip地址（安卓不能实时检测调整iptables，会软重启或者耗电加大）
不知道有没有帮助

**Comment by csy19960309** [comment]
> 在使用[https://github.com/kalasutra/Clash_For_Magisk](url)早期tproxy版本的时候也会有这个问题
> 目前那里的解决办法是在每次启动时就探测现有连接到wifi获取的ip地址（安卓不能实时检测调整iptables，会软重启或者耗电加大）
> 不知道有没有帮助

请问你用的core是哪个版本？我之前和你遇到同样问题，后来把官方repo里的core换成这个repo的最新release中的core就好了。

**Comment by wsvg14** [comment]
> > 在使用[https://github.com/kalasutra/Clash_For_Magisk](url)早期tproxy版本的时候也会有这个问题
> > 目前那里的解决办法是在每次启动时就探测现有连接到wifi获取的ip地址（安卓不能实时检测调整iptables，会软重启或者耗电加大）
> > 不知道有没有帮助
> 
> 请问你用的core是哪个版本？我之前和你遇到同样问题，后来把官方repo里的core换成这个repo的最新release中的core就好了。

指的是哪个，xray还是clash

**Comment by csy19960309** [comment]
> > > 在使用[https://github.com/kalasutra/Clash_For_Magisk](url)早期tproxy版本的时候也会有这个问题
> > > 目前那里的解决办法是在每次启动时就探测现有连接到wifi获取的ip地址（安卓不能实时检测调整iptables，会软重启或者耗电加大）
> > > 不知道有没有帮助
> > 
> > 
> > 请问你用的core是哪个版本？我之前和你遇到同样问题，后来把官方repo里的core换成这个repo的最新release中的core就好了。
> 
> 指的是哪个，xray还是clash

xray. 我是指你提的这个issue本身，不该quote reply应该直接评论的 _(:з)∠)_

**Comment by wsvg14** [comment]
@csy19960309 之前测试的时候是这个repo的1.3改版，不过更新1.4之后自己换的官方还没试

**Comment by CerteKim** [comment]
Xray现在已经可以解决之前的那个问题了，但是相应的要修改配置文件

**Comment by wsvg14** [comment]
回来再跑了下，在路由里面加了禁止tproxy自己连自己的规则之后，在error里面将不会有任何提示，但是在查看网速的时候可以看到流过几十mb/s的数据量经过

**Comment by CerteKim** [comment]
可以测试一下最新的版本

在终端输入：   
`su -c /data/adb/xray/scripts/watch.service start`

此脚本会每隔一段时间检测一次 ip。
此后再在 XRAY 链中插入绕过此 ip 的规则。

虽然不是一个优雅的解决方式，但没有想到什么别的办法了。

**Comment by wsvg14** [comment]
> 可以测试一下最新的版本
> 
> 在终端输入：
> `su -c /data/adb/xray/scripts/watch.service start`
> 
> 此脚本会每隔一段时间检测一次 ip。
> 此后再在 XRAY 链中插入绕过此 ip 的规则。
> 
> 虽然不是一个优雅的解决方式，但没有想到什么别的办法了。

测试过了，打开飞行模式并且关闭流量(防止抢先获取)的情况下确实解决解决了回环
不过现在这个版本ipv6解析有问题，当然这不是这篇讨论范围内了
还是先用回v2rayng了

**Comment by CerteKim** [comment]
1.5.0 版本修复了这个问题（可能
