### ISSUE TITLE
MIUI系统下应用双开的Google Play服务耗电过高

### ISSUE THREAD

**Issue by kanshurichard** [CerteKim/Xray4Magisk#16]
大概是应用双开的Google Play一直试图连接Google网络，但无法连接，导致耗电

临时解决方案：

如果双开的应用不需要Google Play服务，可以通过以下命令删除

`adb shell pm uninstall --user 999 com.google.android.gms`

**Comment by CerteKim** [comment]
是用全局模式还是开了黑白名单？
