### ISSUE TITLE
dns问题

### ISSUE THREAD

**Issue by tooka-death** [CerteKim/Xray4Magisk#19]
Xray 1.3.1 (Xray, Penetrates Everything.) Custom (go1.16 android/arm64)
A unified platform for anti-censorship.
2021/03/31 09:28:41 Using confdir from arg: /data/xray/confs
2021/03/31 09:28:41 [Info] infra/conf/serial: Reading config: /data/xray/confs/base.json
2021/03/31 09:28:41 [Info] infra/conf/serial: Reading config: /data/xray/confs/dns.json
xctl> [ /data/xray/confs/dns.json ] prepended outbound with tag:  dns-in
2021/03/31 09:28:41 [Info] infra/conf/serial: Reading config: /data/xray/confs/proxy.json
xctl> [ /data/xray/confs/proxy.json ] prepended outbound with tag:  proxy
2021/03/31 09:28:41 [Info] infra/conf/serial: Reading config: /data/xray/confs/routing.json
2021/03/31 09:28:41 [Info] infra/conf/serial: Reading config: /data/xray/confs/xray-api.json
xctl> [ /data/xray/confs/xray-api.json ] appended inbound with tag:  api
2021/03/31 09:28:42 [Debug] app/log: Logger started
2021/03/31 09:28:42 [Info] app/dns: DNS: created Remote DOH client for https://1.1.1.1/dns-query
2021/03/31 09:28:42 [Info] app/dns: DNS: created Local DOH client for https://223.5.5.5/dns-query
2021/03/31 09:28:42 [Info] app/dns: DNS: created Local DOH client for https://doh.pub/dns-query
2021/03/31 09:28:42 [Info] app/dns: DNS: created udp client inited for 223.5.5.5:53
2021/03/31 09:28:42 [Info] app/dns: DNS: created localhost client
2021/03/31 09:28:42 [Debug] app/stats: create new counter inbound>>>proxy-in>>>traffic>>>uplink
2021/03/31 09:28:42 [Debug] app/stats: create new counter inbound>>>proxy-in>>>traffic>>>downlink
2021/03/31 09:28:42 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:65535
2021/03/31 09:28:42 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>uplink
2021/03/31 09:28:42 [Debug] app/stats: create new counter inbound>>>api>>>traffic>>>downlink
2021/03/31 09:28:42 [Debug] app/proxyman/inbound: creating stream worker on 127.0.0.1:65534
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>proxy>>>traffic>>>uplink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>proxy>>>traffic>>>downlink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>dns-in>>>traffic>>>uplink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>dns-in>>>traffic>>>downlink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>uplink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>direct>>>traffic>>>downlink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>block>>>traffic>>>uplink
2021/03/31 09:28:42 [Debug] app/stats: create new counter outbound>>>block>>>traffic>>>downlink
2021/03/31 09:28:42 [Info] transport/internet/tcp: listening TCP on 127.0.0.1:65534
2021/03/31 09:28:42 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:65535
2021/03/31 09:28:42 [Info] transport/internet/udp: listening UDP on 0.0.0.0:65535
2021/03/31 09:28:42 [Warning] core: Xray 1.3.1 started
2021/03/31 09:28:46 [Debug] transport/internet/udp: UDP original destination: udp:111.8.14.18:53
2021/03/31 09:28:46 [Debug] [4207945946] proxy/dokodemo: processing connection from: 10.230.197.219:11929
2021/03/31 09:28:46 [Info] [4207945946] proxy/dokodemo: received request for 10.230.197.219:11929
2021/03/31 09:28:46 [Info] [4207945946] app/dispatcher: taking detour [dns-in] for [udp:111.8.14.18:53]
2021/03/31 09:28:46 [Info] [4207945946] proxy/dns: handling DNS traffic to udp:111.8.14.18:53
2021/03/31 09:28:46 [Info] app/dns: DOH//1.1.1.1 querying: 10.0.0.172.
2021/03/31 09:28:46 [Info] app/dispatcher: taking detour [direct] for [tcp:1.1.1.1:443]
2021/03/31 09:28:46 [Info] proxy/freedom: opening connection to tcp:1.1.1.1:443
2021/03/31 09:28:46 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:46 [Debug] transport/internet/udp: UDP original destination: udp:111.8.14.18:53
2021/03/31 09:28:46 [Debug] [3136935590] proxy/dokodemo: processing connection from: 10.230.197.219:33680
2021/03/31 09:28:46 [Info] [3136935590] proxy/dokodemo: received request for 10.230.197.219:33680
2021/03/31 09:28:46 [Info] [3136935590] app/dispatcher: taking detour [dns-in] for [udp:111.8.14.18:53]
2021/03/31 09:28:46 [Info] [3136935590] proxy/dns: handling DNS traffic to udp:111.8.14.18:53
2021/03/31 09:28:46 [Debug] transport/internet/udp: UDP original destination: udp:111.8.14.18:53
2021/03/31 09:28:46 [Debug] [3041946481] proxy/dokodemo: processing connection from: 10.230.197.219:58800
2021/03/31 09:28:46 [Info] [3041946481] proxy/dokodemo: received request for 10.230.197.219:58800
2021/03/31 09:28:46 [Info] [3041946481] app/dispatcher: taking detour [dns-in] for [udp:111.8.14.18:53]
2021/03/31 09:28:46 [Info] [3041946481] proxy/dns: handling DNS traffic to udp:111.8.14.18:53
2021/03/31 09:28:46 [Debug] app/dns: domain mtalk.google.com matches following rules: [geosite:geolocation-!cn(DNS idx:0)]
2021/03/31 09:28:46 [Debug] app/dns: domain mtalk.google.com uses following DNS first: [DOH//1.1.1.1]
2021/03/31 09:28:46 [Debug] app/dns: domain ntp.ntsc.ac.cn matches following rules: [geosite:cn(DNS idx:1) geosite:cn(DNS idx:2)]
2021/03/31 09:28:46 [Debug] app/dns: domain ntp.ntsc.ac.cn uses following DNS first: [DOHL//223.5.5.5 DOHL//doh.pub]
2021/03/31 09:28:46 [Info] app/dns: DOH//1.1.1.1 querying: mtalk.google.com.
2021/03/31 09:28:46 [Info] app/dns: DOHL//223.5.5.5 querying: ntp.ntsc.ac.cn.
2021/03/31 09:28:46 [Info] app/dispatcher: taking detour [direct] for [tcp:1.1.1.1:443]
2021/03/31 09:28:46 [Info] proxy/freedom: opening connection to tcp:1.1.1.1:443
2021/03/31 09:28:46 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:47 [Info] app/dns: DOHL//223.5.5.5 got answer: ntp.ntsc.ac.cn. TypeA -> [114.118.7.161 114.118.7.163] 310.175209ms
2021/03/31 09:28:47 [Debug] app/dns: domain ntp.ntsc.ac.cn expectIPs [114.118.7.161 114.118.7.163] matched at server DOHL//223.5.5.5 idx:1
2021/03/31 09:28:47 [Debug] transport/internet/udp: UDP original destination: udp:114.118.7.161:123
2021/03/31 09:28:47 [Debug] [1265672596] proxy/dokodemo: processing connection from: 10.230.197.219:45396
2021/03/31 09:28:47 [Info] [1265672596] proxy/dokodemo: received request for 10.230.197.219:45396
2021/03/31 09:28:47 [Info] [1265672596] app/dispatcher: taking detour [direct] for [udp:114.118.7.161:123]
2021/03/31 09:28:47 [Info] [1265672596] proxy/freedom: opening connection to udp:114.118.7.161:123
2021/03/31 09:28:50 [Info] app/dns: failed to lookup ip for domain 10.0.0.172 at server DOH//1.1.1.1 > context deadline exceeded
2021/03/31 09:28:50 [Error] app/dns: failed to retrieve response for 10.0.0.172. > Post "https://1.1.1.1/dns-query": context deadline exceeded
2021/03/31 09:28:50 [Info] app/dns: DOHL//223.5.5.5 querying: 10.0.0.172.
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] app/dns: DOHL//223.5.5.5 got answer: 10.0.0.172. TypeA -> [] 99.729375ms
2021/03/31 09:28:50 [Info] app/dns: failed to lookup ip for domain 10.0.0.172 at server DOHL//223.5.5.5 > empty response
2021/03/31 09:28:50 [Debug] transport/internet/udp: UDP original destination: udp:111.8.14.18:53
2021/03/31 09:28:50 [Debug] [1779629125] proxy/dokodemo: processing connection from: 10.230.197.219:15195
2021/03/31 09:28:50 [Info] [1779629125] proxy/dokodemo: received request for 10.230.197.219:15195
2021/03/31 09:28:50 [Info] [1779629125] app/dispatcher: taking detour [dns-in] for [udp:111.8.14.18:53]
2021/03/31 09:28:50 [Info] [1779629125] proxy/dns: handling DNS traffic to udp:111.8.14.18:53
2021/03/31 09:28:50 [Info] app/dns: DOH//1.1.1.1 querying: 10.0.0.172.
2021/03/31 09:28:50 [Info] app/dispatcher: taking detour [direct] for [tcp:1.1.1.1:443]
2021/03/31 09:28:50 [Info] proxy/freedom: opening connection to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] app/dns: failed to lookup ip for domain mtalk.google.com at server DOH//1.1.1.1 > context deadline exceeded
2021/03/31 09:28:50 [Debug] app/dns: domain mtalk.google.com at server DOH//1.1.1.1 idx:0 already lookup failed, just ignore
2021/03/31 09:28:50 [Error] app/dns: failed to retrieve response for mtalk.google.com. > Post "https://1.1.1.1/dns-query": context deadline exceeded
2021/03/31 09:28:50 [Info] app/dns: DOHL//223.5.5.5 querying: mtalk.google.com.
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] app/dns: DOHL//223.5.5.5 got answer: mtalk.google.com. TypeA -> [74.125.203.188] 175.944843ms
2021/03/31 09:28:50 [Info] app/dns: failed to lookup ip for domain mtalk.google.com at server DOHL//223.5.5.5 > expectIPs not match
2021/03/31 09:28:50 [Info] app/dns: DOHL//doh.pub querying: mtalk.google.com.
2021/03/31 09:28:50 [Error] app/dns: failed to retrieve response for mtalk.google.com. > Post "https://doh.pub/dns-query": dial tcp: lookup doh.pub on [::1]:53: dial udp [::1]:53: connect: network is unreachable
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:50 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:51 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:51 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:51 [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:1.1.1.1:443 > common/retry: [dial tcp 1.1.1.1:443: i/o timeout] > common/retry: all retry attempts failed
2021/03/31 09:28:51 [Debug] transport/internet/udp: UDP original destination: udp:211.142.211.124:53
2021/03/31 09:28:51 [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:1.1.1.1:443 > common/retry: [dial tcp 1.1.1.1:443: i/o timeout] > common/retry: all retry attempts failed
2021/03/31 09:28:51 [Debug] [901853415] proxy/dokodemo: processing connection from: 10.230.197.219:3528
2021/03/31 09:28:51 [Info] [901853415] proxy/dokodemo: received request for 10.230.197.219:3528
2021/03/31 09:28:51 [Info] [901853415] app/dispatcher: taking detour [dns-in] for [udp:211.142.211.124:53]
2021/03/31 09:28:51 [Info] [901853415] proxy/dns: handling DNS traffic to udp:211.142.211.124:53
2021/03/31 09:28:51 [Debug] app/dns: domain mtalk.google.com matches following rules: [geosite:geolocation-!cn(DNS idx:0)]
2021/03/31 09:28:51 [Debug] app/dns: domain mtalk.google.com uses following DNS first: [DOH//1.1.1.1]
2021/03/31 09:28:51 [Info] app/dns: DOH//1.1.1.1 querying: mtalk.google.com.
2021/03/31 09:28:51 [Info] app/dispatcher: taking detour [direct] for [tcp:1.1.1.1:443]
2021/03/31 09:28:51 [Info] proxy/freedom: opening connection to tcp:1.1.1.1:443
2021/03/31 09:28:51 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:54 [Info] app/dns: failed to lookup ip for domain 10.0.0.172 at server DOH//1.1.1.1 > context deadline exceeded
2021/03/31 09:28:54 [Info] app/dns: DOHL//223.5.5.5 cache HIT 10.0.0.172 -> [] > empty response
2021/03/31 09:28:54 [Info] app/dns: failed to lookup ip for domain 10.0.0.172 at server DOHL//223.5.5.5 > empty response
2021/03/31 09:28:54 [Error] app/dns: failed to retrieve response for 10.0.0.172. > Post "https://1.1.1.1/dns-query": context deadline exceeded
2021/03/31 09:28:54 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:54 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:54 [Info] app/dns: failed to lookup ip for domain mtalk.google.com at server DOHL//doh.pub > context deadline exceeded
2021/03/31 09:28:54 [Debug] app/dns: UDP:223.5.5.5:53 querying DNS for: mtalk.google.com.
2021/03/31 09:28:54 [Debug] transport/internet/udp: dispatch request to: udp:223.5.5.5:53
2021/03/31 09:28:54 [Info] transport/internet/udp: establishing new connection for udp:223.5.5.5:53
2021/03/31 09:28:54 [Info] app/dispatcher: taking detour [direct] for [udp:223.5.5.5:53]
2021/03/31 09:28:54 [Info] proxy/freedom: opening connection to udp:223.5.5.5:53
2021/03/31 09:28:55 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:55 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:55 [Info] app/dns: failed to lookup ip for domain mtalk.google.com at server DOH//1.1.1.1 > context deadline exceeded
2021/03/31 09:28:55 [Debug] app/dns: domain mtalk.google.com at server DOH//1.1.1.1 idx:0 already lookup failed, just ignore
2021/03/31 09:28:55 [Debug] app/dns: DOHL//223.5.5.5 cache HIT mtalk.google.com -> [74.125.203.188]
2021/03/31 09:28:55 [Info] app/dns: failed to lookup ip for domain mtalk.google.com at server DOHL//223.5.5.5 > expectIPs not match
2021/03/31 09:28:55 [Info] app/dns: DOHL//doh.pub querying: mtalk.google.com.
2021/03/31 09:28:55 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:55 [Info] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:1.1.1.1:443 > common/retry: [dial tcp 1.1.1.1:443: i/o timeout] > common/retry: all retry attempts failed
2021/03/31 09:28:55 [Error] app/dns: failed to retrieve response for mtalk.google.com. > Post "https://1.1.1.1/dns-query": context deadline exceeded
2021/03/31 09:28:55 [Error] app/dns: failed to retrieve response for mtalk.google.com. > Post "https://doh.pub/dns-query": dial tcp: lookup doh.pub on [::1]:53: dial udp [::1]:53: connect: network is unreachable
2021/03/31 09:28:55 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:56 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:56 [Info] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:443
2021/03/31 09:28:56 [Debug] transport/internet/udp: UDP original destination: udp:111.8.14.18:53
2021/03/31 09:28:56 [Debug] app/dns: domain mtalk.google.com matches following rules: [geosite:geolocation-!cn(DNS idx:0)]
2021/03/31 09:28:56 [Debug] app/dns: domain mtalk.google.com uses following DNS first: [DOH//1.1.1.1]

**Comment by CerteKim** [comment]
自己修改 /data/xray/confs/dns.json
