### ISSUE TITLE
SELinux要求？

### ISSUE THREAD

**Issue by alan20210202** [CerteKim/Xray4Magisk#23]
在SELinux为enforcing的情况下，service.log 出现 error calling service activity 的报错。在SELinux切至permissive时正常。

请问是否会对使用带来影响？以及可否在启动服务时短暂开启selinux permissive来确保安全性？（相对于全时段selinux permissive而言）

**Comment by CerteKim** [comment]
这是在开启模块（先前为关闭状态），尝试开启再关闭飞行模式时所报的错。

这一步是为了清除 Android netd 中缓存的 dns 数据（很遗憾暂时没有除此之外的其他办法）。

理论上不会造成重大影响，可以忽略这个错误。


没有操作 SElinux 的想法。

**Comment by alan20210202** [comment]
明白了，所以如果报错的话就说明dns缓存没有清空？导致之后的解析有可能返回错误的缓存结果？还是说报错的同时其实缓存也清了

**Comment by CerteKim** [comment]
报错就说明没有清理缓存。

至于有没有影响就要看 dns 污染的情况了。
