### ISSUE TITLE
可以代理 SOCKS/HTTP 端口吗

### ISSUE THREAD

**Issue by SukiEva** [CerteKim/Xray4Magisk#24]
可以和v24Magisk一样，在本地放一个1080的SOCKET代理，这样1DM+代理下载和火狐PAC代理会方便很多

**Comment by CerteKim** [comment]
可以自己修改配置文件添加新的inbound

**Comment by SukiEva** [comment]
好的，我去学习一下，另外安卓11的文件在data/xray里，data/adb下没有xray文件夹

**Comment by CerteKim** [comment]
注意你的 xray4magisk 版本。。1.4.0 才移动到 /data/adb/xray，旧版都是 /data/xray
