### ISSUE TITLE
安卓11，必须开启热点，不然即使开启服务也无法代理

### ISSUE THREAD

**Issue by ikdataa** [CerteKim/Xray4Magisk#27]
开启服务的同时必须开启热点，关闭热点，不一会就无法代理，再开启热点，立即又可以代理
而且，首次开机必须先开启一次热点，不然连服务都无法启动

**Comment by CerteKim** [comment]
请提供一下开启热点时运行模块的日志，和关闭热点时运行模块的日志

**Comment by BaileyZyp** [comment]
我安卓10也这样，用的ROM是PixelExperience

**Comment by BaileyZyp** [comment]
早上我用的Android11，用的ROM是DerpFest，网络正常但是开热点连接热点的手机没网，我还以为是Android11的问题就刷了个Android没想到问题更奇葩

**Comment by BaileyZyp** [comment]
@CerteKim 模块运行日志是哪个文件？

**Comment by BaileyZyp** [comment]
PixelExperience Android 10和Android 11都是这样的

**Comment by BaileyZyp** [comment]
[error.log](https://github.com/CerteKim/Xray4Magisk/files/6481840/error.log)
代理信息我替换掉了其他没动

**Comment by CerteKim** [comment]
#12

**Comment by BaileyZyp** [comment]
> #12

感谢，已解决

**Comment by BaileyZyp** [comment]
`app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)`
@CerteKim 我开热点后有手机连接就一直输出这个警告，我该如何解决
