### ISSUE TITLE
无法开启透明代理

### ISSUE THREAD

**Issue by tooka-death** [CerteKim/Xray4Magisk#28]
[Info]: Starting xray service.RTNETLINK` answers: No such file or directory
using ipv4
[Info]: cleaning mangle iptables
cleaning ipv4
[Info]: creating mangle chain
netstat: /proc/21369: No such file or directory
netstat: /proc/21370: No such file or directory
[Info]: creating proxy
[Error]: Start xray service Failed.

Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 android/arm64)
A unified platform for anti-censorship.
2021/05/05 00:39:41 Using confdir from arg: /data/adb/xray/confs
2021/05/05 00:39:41 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/base.json
2021/05/05 00:39:41 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/dns.json
2021/05/05 00:39:41 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/proxy.json
xctl> [ /data/adb/xray/confs/proxy.json ] prepended outbound with tag:  proxy
2021/05/05 00:39:41 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/routing.json
xctl> [ /data/adb/xray/confs/xray-api.json ] appended inbound with tag:  api
2021/05/05 00:39:41 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-api.json
2021/05/05 00:39:41 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-web.json
xctl> [ /data/adb/xray/confs/xray-web.json ] appended inbound with tag:  web
Failed to start: main: failed to create server > app/log: failed to initialize access logger > open /data/xray/run/access.log: no such file or directory

**Comment by CerteKim** [comment]
修改 base.json 调整 log 文件位置，注意看 release note
