### ISSUE TITLE
infra/conf: XTLS doesn't supports vmess for now.

### ISSUE THREAD

**Issue by kalikai** [CerteKim/Xray4Magisk#29]
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 android/arm64)
A unified platform for anti-censorship.
2021/05/05 03:36:01 Using confdir from arg: /data/adb/xray/confs
2021/05/05 03:36:01 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/base.json
2021/05/05 03:36:01 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/dns.json
xctl> [ /data/adb/xray/confs/proxy.json ] prepended outbound with tag:  proxy
2021/05/05 03:36:01 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/proxy.json
2021/05/05 03:36:01 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/routing.json
2021/05/05 03:36:01 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-api.json
xctl> [ /data/adb/xray/confs/xray-api.json ] appended inbound with tag:  api
2021/05/05 03:36:01 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-web.json
xctl> [ /data/adb/xray/confs/xray-web.json ] appended inbound with tag:  web
Failed to start: mai

**Comment by kalikai** [comment]
How to solve this problem?

**Comment by CerteKim** [comment]
Check your config files.

Prebuilt config files are templates.
