### ISSUE TITLE
[Bug] 路由不起作用

### ISSUE THREAD

**Issue by proxy-rules** [CerteKim/Xray4Magisk#3]
请求被iptables转发到dnscrypt-proxy解析，配置中路由`domain`节点失效。

https://github.com/CerteKim/Xray4Magisk/blob/c7ab8e68e02e9b41dbdf675c9052768487563285/xray/etc/config.json.example#L104-L117

**Comment by CerteKim** [comment]
@proxy-rules 
好，谢谢反馈。

~~(°ー°〃)这其实是v2rayN导出的规则~~

**Comment by CerteKim** [comment]
现在已经使用xray来接管dns了所以可以close issue了❤(ӦｖӦ｡)
