### ISSUE TITLE
Start xray service Failed

### ISSUE THREAD

**Issue by brijagstu7** [CerteKim/Xray4Magisk#30]
/data/adb/xray/run/service.log  : 
```
[Info]: Starting xray service.
[Error]: Start xray service Failed.
```

**Comment by brijagstu7** [comment]
我用的是Android 11，Oneplus7  PixelExperience

**Comment by brijagstu7** [comment]
> 看 error.log

Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 android/arm64)
A unified platform for anti-censorship.
2021/05/10 12:55:59 Using confdir from arg: /data/adb/xray/confs
xctl> [ /data/adb/xray/confs/proxy.json ] prepended outbound with tag:  proxy
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/base.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/dns.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/proxy.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/routing.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-api.json
xctl> [ /data/adb/xray/confs/xray-api.json ] appended inbound with tag:  api
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-web.json
xctl> [ /data/adb/xray/confs/xray-web.json ] appended inbound with tag:  web
Failed to start: main: failed to create server > app/log: failed to initialize access logger > open /data/xray/run/access.log: no such file or directory

**Comment by brijagstu7** [comment]
> 看 error.log

Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 android/arm64)
A unified platform for anti-censorship.
2021/05/10 12:55:59 Using confdir from arg: /data/adb/xray/confs
xctl> [ /data/adb/xray/confs/proxy.json ] prepended outbound with tag:  proxy
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/base.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/dns.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/proxy.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/routing.json
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-api.json
xctl> [ /data/adb/xray/confs/xray-api.json ] appended inbound with tag:  api
2021/05/10 12:55:59 [Info] infra/conf/serial: Reading config: /data/adb/xray/confs/xray-web.json
xctl> [ /data/adb/xray/confs/xray-web.json ] appended inbound with tag:  web
Failed to start: main: failed to create server > app/log: failed to initialize access logger > open /data/xray/run/access.log: no such file or directory

**Comment by brijagstu7** [comment]
我是先下载xray-core到/sdcard/Download，然后安装模块的，安装完重启就得到这些log。之后我把模块disable，然后再enable，就不能联网了（数据流量和wifi都不行）

**Comment by brijagstu7** [comment]
我试了下把proxy.json改成我的节点，重启，没区别

**Comment by CerteKim** [comment]
还是 base.json 没有修改 log 文件路径的问题。。。

**Comment by CerteKim** [comment]
1.4.0 是 breaking change

**Comment by CerteKim** [comment]
嗯

**Comment by brijagstu7** [comment]
我按照这个改了

> @CerteKim 是把`/data/xray/run/access.log`改成`/data/adb/xray/run/access.log`吗

重启之后，看了error.log，没有再报错，然后我改了proxy.json。
这个时候不能联网。
然后在magisk里面把模块关闭了，奇怪的是仍然不能联网（按照说明不应该就取消代理了吗）
重启，error.log又报错了
```
Xray 1.4.2 (Xray, Penetrates Everything.) Custom (go1.16.2 android/arm64)
A unified platform for anti-censorship.
2021/05/10 14:05:32 Using confdir from arg: /data/adb/xray/confs
2021/05/10 14:05:32 [Info] infra/conf/serial: Reading config: /data/adb/xray/con
2021/05/10 14:05:32 [Info] infra/conf/serial: Reading config: /data/adb/xray/con
2021/05/10 14:05:32 [Info] infra/conf/serial: Reading config: /data/adb/xray/con
Failed to start: main: failed to load config files: [/data/adb/xray/confs/base.
```

**Comment by brijagstu7** [comment]
我改proxy.json是这样改的：
原本我电脑里的config.json里面，output是这一段：
```
{
"outbounds": [
    {
      "mux": {
        "enabled": false,
        "concurrency": 8
      },
      "protocol": "vmess",
      "streamSettings": {
        "network": "tcp",
        "tcpSettings": {
          "header": {
            "type": "none"
          }
        },
        "security": "none"
      },
      "tag": "proxy",
      "settings": {
        "vnext": [
          {
            "address": "35.***.152.181",
            "users": [
              {
                "id": "bb029ba9-38ab-4230-82de-a2e1570a5215",
                "alterId": 0,
                "level": 0,
                "security": "aes-128-gcm"
              }
            ],
            "port": 58226
          }
        ]
      }
    },
    {
      "tag": "direct",
      "protocol": "freedom",
      "settings": {
        "domainStrategy": "UseIP",
        "redirect": "",
        "userLevel": 0
      }
    },
    {
      "tag": "block",
      "protocol": "blackhole",
      "settings": {
        "response": {
          "type": "none"
        }
      }
    }
  ]
  }
```
在默认的proxy.json的基础上我做了这些更改：
```
"outbounds": [
        {
            "tag": "proxy",
            "protocol": "VMESS",
            "settings": {
                "vnext": [
                    {
                ->        "address": "35.220.152.181",
                ->        "port": 58226,
                        "users": [
                            {
                ->                "id": "bb029ba9-38ab-4230-82de-a2e1570a5215",
                                  "alterId": 0,
                 ->               "security": "none",
                 --               "encryption": "none",
                 --               "flow": "xtls-rprx-splice"
                 ++               "level": 0,
                            }                             
                        ]    
                    }    
                ],   
                "servers": null,
                "response": null
                },                                                               
            "streamSettings": {                                              
                "network": "tcp",                                            
                "security": "xtls",                                          
                "xtlsSettings": {                                            
                    "allowInsecure": false,                                  
                    "serverName": "one.one.one.one"                          
                },                                                           
                "tcpSettings": null,                                         
                "sockopt": {                                                 
                    "domainStrategy": "UseIP"             
                }                                         
            },                                            
            "mux": {                                      
                "concurrency": -1,                        
                "enabled": false                   
            }                                      
        }                                          
    ]         
```
是哪些关键字段没填对吗

**Comment by brijagstu7** [comment]
问题是手头上没有VLESS协议的配置文件

**Comment by CerteKim** [comment]
看报错的最后一行。。。¯\_༼ •́ ͜ʖ •̀ ༽_/¯
多看看文档。。xray 怎么用

**Comment by brijagstu7** [comment]
文档是这个吧`xtls.github.io/config`
看的一脸蒙蔽呀 文档不是说支持VMESS的嘛

**Comment by CerteKim** [comment]
文档那里说 xtls 支持 vmess 了。。。？
```
"xtlsSettings": {
```
改成
```
"tlsSettings": {
```

**Comment by brijagstu7** [comment]
> 文档那里说 xtls 支持 vmess 了。。。？
> 
> ```
> "xtlsSettings": {
> ```
> 
> 改成
> 
> ```
> "tlsSettings": {
> ```

诶 我怎么感觉是要把
`"allowInsecure": false,   `
->
`"allowInsecure": true,   `

**Comment by brijagstu7** [comment]
每次改下配置还要重启手机好麻烦压

**Comment by brijagstu7** [comment]
好了这下没报错了: )
可以联网了 但是连不了谷歌
error.log里面1000多行 没有[ERROR]但是有几行：
`failed to lookup ip for domain clients4.google.com at server DOHL//1.1.1.1 > context deadline exceeded`

**Comment by brijagstu7** [comment]
@CerteKim 哦看到了有[ERROR]
` app/dns: failed to lookup ip for domain clients4.google.com at server DOH//223.5.5.5 > expectIPs not match`

**Comment by brijagstu7** [comment]
我感觉是要改一下这2个位置中的一个 但是很奇怪文档里面好像没介绍streamSettings
```
"streamSettings": {                                              
                "network": "tcp",                                            
                "security": "tls",                                           
                "tlsSettings": {                                             
                    "allowInsecure": true,                                   
---->           "serverName": "one.one.one.one"                          
                },                                                           
                "tcpSettings": null,                     
                "sockopt": {                             
---->            "domainStrategy": "UseIP"            
                }                                  
            }
```

**Comment by brijagstu7** [comment]
昨晚忽略了service.log，但是在做完xtls->tls的改动之后service.log就有问题的
```
[Info]: Starting xray service.                                        
RTNETLINK answers: No such file or directory                          
using ipv4                                     
[Info]: cleaning mangle iptables               
cmd: Failure calling service settings: Failed transaction (2147483646)
cleaning ipv4                                                         
[Info]: creating mangle chain                                         
[Info]: creating proxy                                                
cmd: Failure calling service activity: Failed transaction (2147483646)
[Info]: xray service is running. ( PID: 12689 )                       
cmd: Failure calling service settings: Failed transaction (2147483646)
cmd: Failure calling service activity: Failed transaction (2147483646)
```
本来期望可以不用过多操作就能实现透明代理的，因为不想学太多计划之外的知识（主要是最近还要做毕业设计），但是还是有这么多问题，难道Android设备的内核之间差异有那么大嘛

**Comment by CerteKim** [comment]
SELinux 的问题，忽略即可

**Comment by brijagstu7** [comment]
> 好了这下没报错了: )
> 可以联网了 但是连不了谷歌
> error.log里面1000多行 没有[ERROR]但是有几行：
> `failed to lookup ip for domain clients4.google.com at server DOHL//1.1.1.1 > context deadline exceeded`

那这个问题要怎么解决呢 @CerteKim

**Comment by CerteKim** [comment]
可能你的网络环境连不上 1.1.1.1 咯。
不用 DoH 试试吧

**Comment by brijagstu7** [comment]
> 可能你的网络环境连不上 1.1.1.1 咯。
> 不用 DoH 试试吧

我换成233.5.5.5了还是不行呀

**Comment by brijagstu7** [comment]
那要是禁用DoH是删去这一行吗？ @CerteKim 
```
{
  "dns": {
    "hosts": {
      "domain:googleapis.cn": "googleapis.com"
    },
    "servers": [
->  "https+local://1.1.1.1/dns-query",
      {
        "address": "https://223.5.5.5/dns-query",
        "domains": [
          "geosite:cn"
        ],
        "expectIPs": [
          "geoip:cn"
        ]
      }
    ],
    "tag": "dns"
  }
}
```

**Comment by CerteKim** [comment]
你去 xray的群 那里问吧，与模块无关。。。已经歪楼两整天了。。。

**Comment by brijagstu7** [comment]
> 你去 xray的群 那里问吧，与模块无关。。。已经歪楼两整天了。。。

也就今天这个dns问题暂时看来无关吧，之前的那个/data/adb和SELinux问题都是模块应该改善的吧
而且我找不到xray的群 那种适合讨论技术的找不到

**Comment by CerteKim** [comment]
SELinux 无解，除非你为了这点破事把它改成 permissive。
路径问题存粹没人看 release note

xray的群在xray的仓库里面写着。。

**Comment by brijagstu7** [comment]
> SELinux 无解，除非你为了这点破事把它改成 permissive。
> 路径问题存粹没人看 release note
> 
> xray的群在xray的仓库里面写着。。

好吧，是ProjectX那个群吗？原谅我没看x2ray-core只看了x2ray-magisk
我是觉得一个好的软件不应该让用户有过多额外操作吧，至少不应该有和功能相差太远的额外操作
不过还是感谢开发者 反正目前看来是安卓手机上实现透明代理的最有效的方法了

**Comment by brijagstu7** [comment]
简要概括一下所有的解决方法，为后续像我一样不熟悉xray的人提供参考：

1. 改access.log的文件路径
2. 禁用DoH
3. 自己的配置文件(config.json)只复制output条目下的"settings"和"streamSettings"到目标的proxy.json下，proxy.json的其余条目不应改动
