### ISSUE TITLE
1.4.2-2 面具安装显示 unzip error

### ISSUE THREAD

**Issue by tsaiajie** [CerteKim/Xray4Magisk#35]
吉祥物同志 1.4.2-2版本 通过面具安装显示 unzip error
打开压缩包看了下 你是不是直接把文件结构好像不对 直接是一个文件夹 把文件夹解压出来 再压缩成ZIP的话是可以安装得

**Comment by tsaiajie** [comment]
![image](https://user-images.githubusercontent.com/72860622/120111935-5fbebe00-c1a6-11eb-89a3-9240079ddfff.png)

**Comment by CerteKim** [comment]
已重传
