### ISSUE TITLE
怎么关闭热点的代理

### ISSUE THREAD

**Issue by Rasta0501** [CerteKim/Xray4Magisk#36]
有的时候需要开热点，但是pc上有更专业的qv2ray。是配置ignore_out.list吗，但是文档又没说怎么配置

**Comment by Flysky12138** [comment]
填写 `wlan+`

**Comment by CerteKim** [comment]
目前没有关闭热点代理的功能。

**Comment by CerteKim** [comment]
这个[提交](https://github.com/CerteKim/Xray4Magisk/commit/90e55d400e69e2646497bd92b33948cb472f353d) 加入了此功能。
可以自行尝试一下。
