### ISSUE TITLE
支持androd12 beta2么

### ISSUE THREAD

**Issue by heqirong** [CerteKim/Xray4Magisk#37]
magisk正常运行，模块也可以安装和运行，日志无报错，但是无法访问gfw以外

**Comment by CerteKim** [comment]
请详细描述一下你的问题。
或者提供更高日志级别的日志以及配置文件（注意删除敏感信息）。

**Comment by heqirong** [comment]
> 请详细描述一下你的问题。
> 或者提供更高日志级别的日志以及配置文件（注意删除敏感信息）。

覆盖重装一次后，正常了，不过dns配置中的doh一直无法解析我的***.xyz域名，换成114.114.114.114才能
