### ISSUE TITLE
不能打开netflix

### ISSUE THREAD

**Issue by Rasta0501** [CerteKim/Xray4Magisk#38]
配置只改了proxy.json，其他网站可以正常打开，奈飞我ip已经解锁了。现在的情况是奈飞打不开好像直连那样，不提供服务，fast.com测速提示连接不上服务器。

**Comment by CerteKim** [comment]
提供更高日志级别的日志以及配置文件。
注意删除敏感信息。

**Comment by Rasta0501** [comment]
解决了，我是群里那个人。。
