### ISSUE TITLE
failed to load config files

### ISSUE THREAD

**Issue by aixiyu** [CerteKim/Xray4Magisk#4]
this is the log:
"A unified platform for anti-censorship.
2021/01/13 03:29:55 [Info] main/json: Reading config: /data/xray/config.json
Failed to start: main: failed to load config files: [/data/xray/config.json] > infra/conf: invalid field rule > infra/conf: failed to parse domain rule: geosite:google > infra/conf: failed to load geosite: GOOGLE > infra/conf: failed to load file: geosite.dat > infra/conf: failed to open file: geosite.dat > open /system/bin/geosite.dat: no such file or directory"
could you please tell me how to solve it? Thanks a lot.

**Comment by aixiyu** [comment]
请问是只需要改outbounds里的设置吗

**Comment by CerteKim** [comment]
未找到geosite.dat什么的。。提供一下安装时的log
