### ISSUE TITLE
this error nohup:exec setuidgid:no such file or directory

### ISSUE THREAD

**Issue by bcpx** [CerteKim/Xray4Magisk#5]
please help me

**Comment by CerteKim** [comment]
@bcpx  install busybox module from magisk manager

**Comment by bcpx** [comment]
thanks for u help ,ihave solve this problem. now my phone don't have network , i want to use Global proxy ，i have a China Telecom air card ,can you help me or provide me a description of configuration parameters, which I study by myself,thank u big boss

**Comment by csy19960309** [comment]
> thanks for u help ,ihave solve this problem. now my phone don't have network , i want to use Global proxy ，i have a China Telecom air card ,can you help me or provide me a description of configuration parameters, which I study by myself,thank u big boss

Configuration json file can be generated by V2rayN. Then you rename the 'config.json' to 'client.json' and move it to the right place.

**Comment by bcpx** [comment]
Thanks u  ,I try it again. My problem is I config the proxy.json That's why my phone cant't use the proxy. now i will revert the proxy.json   and  add a new file named config.json in the same path /data/xray/confs/ and copy the text from v2rayN config.json to /data/xray/confs/config.json  and enjoy it .That's all right ? Thanks u very much.

**Comment by CerteKim** [comment]
The `proxy,json` is only a part of outbound of full `config.json`. You can copy an outbound object from v2rayN's `config.json`. It just looks like `proxy.json`
Notice: The tag of proxy outbound should be `"tag": "proxy",`

If your use domain name as server address, you need 1.2.2 or lower version.
Or you can use my binary `Xray-android-arm64.zip`. (Read `README.md`)

You shouldn't copy full `config.json` from v2rayN.

**Comment by bcpx** [comment]
THANK you  .I  have resolve  the  problem. That's very  nice,I will donate some  to support  you develop.Do you  have  wechat or alipay QR code.Thank you again.

**Comment by CerteKim** [comment]
@bcpx 

The default routing config bypass LAN and main land China. So, when you browse Chinese websites, you will get your IP; when you browse other websites, you will get your vps IP.

use `ALL` to proxy every apps' traffic.

`bypass` should work.

**Comment by bcpx** [comment]
That's very nice,how can I proxy all location include main land China,means global proxy ,because i also need proxy in china.How can I config the routing ,Thanks you help me ,Happy New Year.

**Comment by CerteKim** [comment]
```json
            {
                "type": "field",
                "inboundTag": [
                    "proxy-in"
                ],
                "outboundTag": "proxy"
            }
```

replace line 28~248

**Comment by bcpx** [comment]
Maybe I have other problem this code  replace line 28~248 in routing.json cant't make my phone heve internet,but i do something other to resolve this problem.I find when i open a website ,it Resolve domain name slowlly,then i find the reason is the block ads function is Affect the speed of domain name resolution。I delete this rule and happy to have fast speed of domain name resolution.But I was happily too early, and when I woke up the next day, the phone disconnected again and I broke down. Finally, thank the author for his help.This is a great plugin, I will continue to study until the problem is solved

**Comment by CerteKim** [comment]
You can try version 1.2.5 with a clean install
Or manually replace dns.json & routing.json from zip file to `/data/xray/confs`
