### ISSUE TITLE
bypass模式导致系统定位异常

### ISSUE THREAD

**Issue by heyxiaobai** [CerteKim/Xray4Magisk#6]
在使用bypass绕过一些国内应用后，系统自带的应用定位会产生异常，比如天气自动定位到Setor Oeste（非vps ip所在地区），希望大佬能帮我解惑，感谢！

pixel 3
Android 11
xray4magisk 1.2.3 （xray-core）

**Comment by CerteKim** [comment]
可以尝试把 /data/xray/routing.json 修改一下

原先的配置是从 v2rayN/v2rayNG 的 “绕过局域网与中国大陆” + “一键导入默认路由规则” 导出来的
